### ISSUE TITLE
[wiki] CommonType-containers: Graphite

### ISSUE THREAD

**Issue by bobh0303** [commontype-standard/commontype#37]
I found the CommonType Containesr wiki to be a good read! Could I suggest a minor tweak to it?  (a good reason to get it into the repo proper ;-) 

The wiki currently says:

> “Graphite” or “SIL Graphite”: alternative layout substream coding format developed by SIL, specialized for linguistic applications

however linguistic applications weren't the driving force behind development of Graphite. I would propose the wiki say:

> “Graphite” or “SIL Graphite”: alternative layout substream coding format developed by SIL, designed to support complex writing systems where the needed shaping behaviors either aren't implemented or aren't possible using OpenType layout

**Comment by simoncozens** [comment]
Thanks, that's a better explanation. I've updated the wiki.
