### ISSUE TITLE
Integrate updates from 1.6 and above

### ISSUE THREAD

**Issue by simoncozens** [commontype-standard/commontype#7]
## 1.6

* GDEF: Mark filtering sets, markglyphsetsdef, GDEF version number
* head: fontDirectionHint deprecated,
* cmap format 13
* cmap, name: "Microsoft" platform -> Windows
* New features: cvar, ltra, ltrm, lnum, onum, rtla, rtlm
* New languages and scripts
* name: format 1 naming, set to zero (name id 15), Unicode Platform Specific encoding ID
* os/2: bit 61, fsSelection

## 1.7

* New tables: CBDT, CBLC, COLR, CPAL, MATH, SVG
* New features: Dotless Forms, Flattened accent forms, Math script style alternates, Required Contextual Alternates and Stretching Glyph Decomposition
* gasp: bit flag
* name: IDs 23, 24
* os/2: version 5, usLowerOpticalPointSize, usUpperOpticalPointSize
* TrueType Collection -> Font Collection. .OTC
* VORG now optional
* New languages and script tags

## 1.8

See updates to ISO/IEC 14496-22:2015 Amendment 1 and draft Amendment 2.

* OpenType variations.
  - New tables: avar, fvar, gvar, HVAR, MVAR, VVAR, STAT
  - Feature Variations common table, VariationIndex table
  - Touched tables: BASE, gasp, GDEF, GPOS, GSUB, head, hhea, jstf, os/2, vhea
  - Common Formats chapter
  - Overview chapter
* New language tags and script tags
* New tables: MERG, meta, SBIX, STAT
* GDEF: Mark attachment class, mark glyph sets, caret value format 3
* BASE: new version
* CFF2
  - touches post
* New features: rvrn, vrtr
* glyf: WE_HAVE_A_TWO_BY_TWO, OVERLAP_COMPOUND, SCALED_COMPONENT_OFFSET and UNSCALED_COMPONENT_OFFSET  (from ISO/IEC)
* GPOS: ValueFormat mask, version
* name: new ID 25, changed ID 6
* SVG: Updates from ISO/IEC

**Comment by davelab6** [comment]
We may need to author this fresh based on FontTools code.

**Comment by simoncozens** [comment]
Yes. I also suggest we omit the MATH table, just in case.

**Comment by davelab6** [comment]
@simoncozens I suggest closing this, and as per discussion in another issue more recently, including MATH

**Comment by simoncozens** [comment]
Yes, this irrelevant now I am working from a clean slate.
